# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kaggle_learning',
                'doc_host': 'https://FarnazO.github.io',
                'git_url': 'https://github.com/FarnazO/kaggle_learning',
                'lib_path': 'kaggle_learning'},
  'syms': {'kaggle_learning.core': {'kaggle_learning.core.foo': ('core.html#foo', 'kaggle_learning/core.py')}}}
