"""This notebook is a test for me to learn how to use kaggle with nbdev."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core_farnaz.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/00_core_farnaz.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
